spring.application.name=order
server.port=8084
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin
spring.datasource.url=jdbc:postgresql://localhost:5432/order_db
spring.datasource.username=app
spring.datasource.password=app
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.use_sql_comments=false

logging.level.org.hibernate.SQL=off
logging.level.org.hibernate.orm.jdbc.bind=warn
logging.level.org.hibernate.type.descriptor.sql=off
logging.level.org.springframework.amqp=warn
logging.level.org.springframework.orm.jpa=warn
logging.level.org.springframework.data=warn
logging.level.org.springframework.transaction=warn
